### ISSUE TITLE
Support yup v1

### ISSUE THREAD

**Issue by HonzaMac** [soc221b/yup-schema-faker#215]
We love this great library which helps us catching bugs during development phase instead from production. ❤️

We would like to upgrade to [yup v1](https://github.com/jquense/yup/releases) which was recently upgraded (after two years in beta). 

Can we somehow help with support for v1?

**Comment by ra100** [comment]
see: https://github.com/iendeavor/yup-schema-faker/tree/v6.x.x

**Comment by iendeavor** [comment]
I personally recommend migrating to [`zod`](https://github.com/colinhacks/zod) for better TypeScript support, I also released the [`zod-schema-faker`](https://github.com/iendeavor/zod-schema-faker) too.

**Comment by HonzaMac** [comment]
Thank you! Looking forward to try it
